-- Add farmer_name column if it doesn't exist
ALTER TABLE farmerlogin 
ADD COLUMN IF NOT EXISTS farmer_name VARCHAR(255) NOT NULL AFTER farmer_id,
MODIFY COLUMN email VARCHAR(255) NOT NULL,
MODIFY COLUMN password VARCHAR(255) NOT NULL,
MODIFY COLUMN phone VARCHAR(20) NOT NULL,
MODIFY COLUMN address TEXT NOT NULL,
MODIFY COLUMN state VARCHAR(100) NOT NULL,
MODIFY COLUMN district VARCHAR(100) NOT NULL;
